### ISSUE TITLE
Missing pip freeze requirements.txt

### ISSUE THREAD

**Issue by DavidJRobertson** [Tarskin/HappyTools#24]
I am unable to install the dependencies easily because the pip freeze requirements.txt file is missing.

**Comment by Tarskin** [comment]
I hadn't added a freeze yet, I will set up a `venv` over the weekend to get a minimal list of requirements.

**Comment by Tarskin** [comment]
@DavidJRobertson Would you be able to verify that you are able to run the software with the added requirements?

**Comment by Tarskin** [comment]
Closing this comment as a fresh python install on a new computer was able to run the program after downloading the requirements.
