### ISSUE TITLE
.pyc files in repository

### ISSUE THREAD

**Issue by DavidJRobertson** [Tarskin/HappyTools#25]
Only the python source files (.py) should be in the repository - the compiled (.pyc) files are not guaranteed to be portable between systems. 

I can see that the `.gitignore` file contains an entry for `*.pyc`, however this must have been added after the the .pyc files were already in the repository, so they would have to be removed manually.

**Comment by DavidJRobertson** [comment]
Actually, this only applies to Demo.pyc

**Comment by Tarskin** [comment]
The `.pyc` file was leftover from a singificantly earlier build as you already assumed. I have manually removed it from the branch
