### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by yochannah** [Tarskin/HappyTools#33]
Hi! I was taking a look at your repo after following the link from your paper and noted that the readme refers to a CONTRIBUTING file, but I couldn't actually find the file...

**Comment by Tarskin** [comment]
Dear Dr Yehudi,

I am in the middle of updating the repository and including some automated
review tools such as codacy, as such the readme already refers to a
CONTRIBUTING file but it's not actually finished yet. I apologize for the
inconvenience and expect that it will be ready by coming Tuesday.

Kind Regards,
Bas Jansen

**Comment by Tarskin** [comment]
Relevant files have been added, will leave this issue open until the end of 2018 with the request that community members contribute or suggest changes as to how this project can be made easily accessible for other contributors.
