### ISSUE TITLE
Baseline correction in batch process?

### ISSUE THREAD

**Issue by abmoran** [Tarskin/HappyTools#55]
Does the batch process function automatically baseline correct a dataset? Or should you open all those data together, select baseline correct, and then "manually" calibrate and quantify?

**Comment by Tarskin** [comment]
BatchProcess should not include baseline correction, this has to be manually performed before prior to saving the chromatograms. However, if there are issues with this please provide the data that is providing an issue.

**Comment by abmoran** [comment]
In this case, it is not possible for me to save the chromatograms (or any chromatograms) using Happytools, therefore I cannot save after performing baseline correction.  Is this a programme issue in this case?

**Comment by abmoran** [comment]
Issue resolved - I saw this was previously resolved so I copied the code and edited the code of the programme that I have and save chromatogram function seems to be working.
