### ISSUE TITLE
Unable to quantify due to 'no attribute peak' 

### ISSUE THREAD

**Issue by abmoran** [Tarskin/HappyTools#56]
I am seeing this error, "Peak' object has no attribute 'peak'. 

But I cannot see how it is missing the peak since I am able to detect in with 'peak detection' and the chromatograms are calibrated. Perhaps it is lower abundant in one of the chromatograms and is therefore not being detected by Happytools?

If I increase the detection window then it begins to quantify the wrong peaks.

Is there any solution or work around? or is it possible that if it is not present in a single chromtogram that it can give the result "n.d." and move onto search for the next peak in the list?

Thanks,

**Comment by Tarskin** [comment]
Would you be able to provide the data and the peak lists (or provide a detailed list of steps required to reproduce this issue?)

**Comment by abmoran** [comment]
[AM036-L-c18-intra-inter-1-1A_Emission_1.txt](https://github.com/Tarskin/HappyTools/files/5090726/AM036-L-c18-intra-inter-1-1A_Emission_1.txt)
[AM036-L-c18-intra-inter-1-2A_Emission_1.txt](https://github.com/Tarskin/HappyTools/files/5090727/AM036-L-c18-intra-inter-1-2A_Emission_1.txt)
[AM036-L-c18-intra-inter-1-3A_Emission_1.txt](https://github.com/Tarskin/HappyTools/files/5090728/AM036-L-c18-intra-inter-1-3A_Emission_1.txt)

**Comment by abmoran** [comment]
Calibrant and analyte files: https://we.tl/t-3nMM6KzK0v (expires in 1 week)

Thanks a lot!

**Comment by Tarskin** [comment]
@abmoran This issue is not occurring with the latest version of the software correct?

**Comment by abmoran** [comment]
@Tarskin indeed, it is not occurring with the latest version!
